src/main/java/com/shishuo/cms/entity/vo/AdminVo.java
/*
 *	Copyright © 2013 Changsha Shishuo Network Technology Co., Ltd. All rights reserved.
 *	长沙市师说网络科技有限公司 版权所有
 *	http://www.shishuo.com
 */

package com.shishuo.cms.entity.vo;

import com.shishuo.cms.entity.Admin;

/**
 * @author Herbert
 * 
 */
public class AdminVo extends Admin {
	private String faceUrl;

	public String getFaceUrl() {
		return faceUrl;
	}

	public void setFaceUrl(String faceUrl) {
		this.faceUrl = faceUrl;
	}

}

src/main/java/com/shishuo/cms/entity/vo/ArticleVo.java
/*
 *	Copyright © 2013 Changsha Shishuo Network Technology Co., Ltd. All rights reserved.
 *	长沙市师说网络科技有限公司 版权所有
 *	http://www.shishuo.com
 */

package com.shishuo.cms.entity.vo;

import java.util.ArrayList;
import java.util.List;

import com.shishuo.cms.entity.Admin;
import com.shishuo.cms.entity.Article;
import com.shishuo.cms.entity.Folder;

/**
 * @author Herbert
 * 
 */
public class ArticleVo extends Article {

	private Admin admin;

	private FolderVo folder;

	private List<AttachmentVo> attachmentList = new ArrayList<AttachmentVo>();

	private List<Folder> folderPathList = new ArrayList<Folder>();

	public Admin getAdmin() {
		return admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public FolderVo getFolder() {
		return folder;
	}

	public void setFolder(FolderVo folder) {
		this.folder = folder;
	}

	public List<AttachmentVo> getAttachmentList() {
		return attachmentList;
	}

	public void setAttachmentList(List<AttachmentVo> attachmentList) {
		this.attachmentList = attachmentList;
	}

	public List<Folder> getFolderPathList() {
		return folderPathList;
	}

	public void setFolderPathList(List<Folder> folderPathList) {
		this.folderPathList = folderPathList;
	}

	public long getFolderId() {
		if (this.getFourthFolderId() != 0) {
			return this.getFourthFolderId();
		} else if (this.getThirdFolderId() != 0) {
			return this.getThirdFolderId();
		} else if (this.getSecondFolderId() != 0) {
			return this.getSecondFolderId();
		} else {
			return this.getFirstFolderId();
		}
	}

}

src/main/java/com/shishuo/cms/entity/vo/AttachmentVo.java
/*
 *	Copyright © 2013 Changsha Shishuo Network Technology Co., Ltd. All rights reserved.
 *	长沙市师说网络科技有限公司 版权所有
 *	http://www.shishuo.com
 */

package com.shishuo.cms.entity.vo;

import com.shishuo.cms.entity.Attachment;

public class AttachmentVo extends Attachment {

}

src/main/java/com/shishuo/cms/action/ArticleAction.java
/*
 *	Copyright © 2013 Changsha Shishuo Network Technology Co., Ltd. All rights reserved.
 *	长沙市师说网络科技有限公司 版权所有
 *	http://www.shishuo.com
 */

package com.shishuo.cms.action;

import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.shishuo.cms.entity.Article;
import com.shishuo.cms.entity.Folder;
import com.shishuo.cms.exception.ArticleNotFoundException;
import com.shishuo.cms.exception.FolderNotFoundException;
import com.shishuo.cms.exception.TemplateNotFoundException;

/**
 * @author Herbert
 * 
 */
@Controller
public class ArticleAction extends BaseAction {

	/**
	 * 一级目录页
	 * 
	 * @param ename
	 * @param pageNum
	 * @param modelMap
	 * @return
	 */
	@RequestMapping(value = "/{firstFolderEname}/{articleId}.htm", method = RequestMethod.GET)
	public String firstFolder(@PathVariable String firstFolderEname,
			@PathVariable long articleId,
			@RequestParam(value = "p", defaultValue = "1") long p,
			ModelMap modelMap) {
		return fourthFolder(firstFolderEname, null, null, null, articleId, p,
				modelMap);
	}

	/**
	 * 二级目录页
	 * 
	 * @param ename
	 * @param pageNum
	 * @param modelMap
	 * @return
	 */
	@RequestMapping(value = "/{firstFolderEname}/{secondFolderEname}/{articleId}.htm", method = RequestMethod.GET)
	public String secondFolder(@PathVariable String firstFolderEname,
			@PathVariable String secondFolderEname, @PathVariable long articleId,
			@RequestParam(value = "p", defaultValue = "1") long p,
			ModelMap modelMap) {
		return fourthFolder(firstFolderEname, secondFolderEname, null, null,
				articleId, p, modelMap);
	}

	/**
	 * 三级目录页
	 * 
	 * @param ename
	 * @param pageNum
	 * @param modelMap
	 * @return
	 */
	@RequestMapping(value = "/{firstFolderEname}/{secondFolderEname}/{thirdFolderEname}/{articleId}.htm", method = RequestMethod.GET)
	public String thirdFolder(@PathVariable String firstFolderEname,
			@PathVariable String secondFolderEname,
			@PathVariable String thirdFolderEname, @PathVariable long articleId,
			@RequestParam(value = "p", defaultValue = "1") long p,
			ModelMap modelMap) {
		return fourthFolder(firstFolderEname, secondFolderEname,
				thirdFolderEname, null, articleId, p, modelMap);
	}

	/**
	 * 四级目录页
	 * 
	 * @param ename
	 * @param pageNum
	 * @param modelMap
	 * @return
	 */
	@RequestMapping(value = "/{firstFolderEname}/{secondFolderEname}/{thirdFolderEname}/{fourthFolderEname}/{articleId}.htm", method = RequestMethod.GET)
	public String fourthFolder(@PathVariable String firstFolderEname,
			@PathVariable String secondFolderEname,
			@PathVariable String thirdFolderEname,
			@PathVariable String fourthFolderEname, @PathVariable long articleId,
			@RequestParam(value = "p", defaultValue = "1") long p,
			ModelMap modelMap) {
		try {
			List<Folder> folderPathList = packageFolderByEname(
					firstFolderEname, secondFolderEname, thirdFolderEname,
					fourthFolderEname, modelMap);
			Article article = fileService.getArticleByArticleId(articleId);
			modelMap.addAttribute("p", p);
			modelMap.addAttribute("article", article);
			return themeService.getArticleTemplate(folderPathList, articleId);
		} catch (FolderNotFoundException e) {
			logger.fatal(e.getMessage());
			return themeService.getTemplatePath("404");
		} catch (TemplateNotFoundException e) {
			logger.fatal(e.getMessage());
			return themeService.getTemplatePath("404");
		} catch (ArticleNotFoundException e) {
			logger.fatal(e.getMessage());
			return themeService.getTemplatePath("404");
		}
	}
}

src/main/java/com/shishuo/cms/action/AuthAction.java
/*
 *	Copyright © 2013 Changsha Shishuo Network Technology Co., Ltd. All rights reserved.
 *	长沙市师说网络科技有限公司 版权所有
 *	http://www.shishuo.com
 */

package com.shishuo.cms.action;

import java.awt.image.BufferedImage;

import javax.imageio.ImageIO;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.validator.routines.EmailValidator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.google.code.kaptcha.impl.DefaultKaptcha;
import com.shishuo.cms.constant.SystemConstant;
import com.shishuo.cms.entity.vo.JsonVo;
import com.shishuo.cms.service.AdminService;
import com.shishuo.cms.util.HttpUtils;

/**
 * @author Herbert
 * 
 */

@Controller
@RequestMapping("/auth")
public class AuthAction extends BaseAction {

	/**
	 * Kaptcha 验证码
	 */
	@Autowired
	private DefaultKaptcha captchaProducer;

	@Autowired
	private AdminService adminService;

	@RequestMapping(value = "admin/login.htm", method = RequestMethod.GET)
	public String adminLogin(HttpServletRequest request, ModelMap modelMap) {
		return "system/login";
	}

	@RequestMapping(value = "admin/logout.htm", method = RequestMethod.GET)
	public String adminLogout(HttpServletRequest request, ModelMap modelMap) {
		request.getSession().removeAttribute(SystemConstant.SESSION_ADMIN);
		return "redirect:" + HttpUtils.getBasePath(request);
	}

	@ResponseBody
	@RequestMapping(value = "admin/login.json", method = RequestMethod.POST)
	public JsonVo<String> adminLogin(
			@RequestParam(value = "email") String email,
			@RequestParam(value = "password") String password,
			@RequestParam(value = "captcha") String captcha,
			HttpServletRequest request, ModelMap modelMap) {
		JsonVo<String> json = new JsonVo<String>();

		try {
			String kaptcha = (String) request.getSession().getAttribute(
					com.google.code.kaptcha.Constants.KAPTCHA_SESSION_KEY);
			if (!EmailValidator.getInstance().isValid(email)) {
				json.getErrors().put("email", "邮件格式错误");
			}
			if (StringUtils.isBlank(password)) {
				json.getErrors().put("password", "密码不能为空");
			} else if (password.length() < 6 && password.length() > 30) {
				json.getErrors().put("password", "密码最少6个字符，最多30个字符");
			}
			// 校验验证码
			if (StringUtils.isNotBlank(kaptcha)
					&& kaptcha.equalsIgnoreCase(captcha)) {

			} else {
				json.getErrors().put("captcha", "验证码错误");
			}
			this.validate(json);

			adminService.adminLogin(email, password, request);

		} catch (Exception e) {
			// 异常，重置验证码
			request.getSession().removeAttribute(
					com.google.code.kaptcha.Constants.KAPTCHA_SESSION_KEY);
			json.setResult(false);
			json.getErrors().put("password", "邮箱或密码错误");
			json.setMsg("change_captcha");
		}
		return json;
	}

	/**
	 * 生成验证码
	 * 
	 * @param request
	 * @param response
	 * @throws Exception
	 */
	@RequestMapping(value = "captcha.htm", method = RequestMethod.GET)
	public void captcha(HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		response.setDateHeader("Expires", 0);
		response.setHeader("Cache-Control",
				"no-store, no-cache, must-revalidate");
		response.addHeader("Cache-Control", "post-check=0, pre-check=0");
		response.setHeader("Pragma", "no-cache");
		response.setContentType("image/jpeg");
		String capText = captchaProducer.createText();
		request.getSession().setAttribute(
				com.google.code.kaptcha.Constants.KAPTCHA_SESSION_KEY, capText);
		BufferedImage bi = captchaProducer.createImage(capText);
		ServletOutputStream out = response.getOutputStream();
		ImageIO.write(bi, "jpg", out);
		try {
			out.flush();
		} finally {
			out.close();
		}
	}
}

src/main/java/com/shishuo/cms/action/BaseAction.java
/*
 *	Copyright © 2013 Changsha Shishuo Network Technology Co., Ltd. All rights reserved.
 *	长沙市师说网络科技有限公司 版权所有
 *	http://www.shishuo.com
 */
package com.shishuo.cms.action;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.ModelMap;

import com.shishuo.cms.entity.Folder;
import com.shishuo.cms.entity.vo.FolderVo;
import com.shishuo.cms.entity.vo.JsonVo;
import com.shishuo.cms.exception.FolderNotFoundException;
import com.shishuo.cms.exception.ValidateException;
import com.shishuo.cms.service.ArticleService;
import com.shishuo.cms.service.ConfigService;
import com.shishuo.cms.service.FolderService;
import com.shishuo.cms.service.TemplateService;

/**
 * 
 * @author Herbert
 * 
 */
public class BaseAction {

	@Autowired
	protected FolderService folderService;

	@Autowired
	protected ArticleService fileService;

	@Autowired
	protected ConfigService configService;

	@Autowired
	protected TemplateService themeService;

	protected final Logger logger = Logger.getLogger(this.getClass());

	/**
	 * 参数校验
	 * 
	 * @param json
	 *            json数据Bean
	 * @throws ValidateException
	 */
	protected <T> void validate(JsonVo<T> json) throws ValidateException {
		if (json.getErrors().size() > 0) {
			json.setResult(false);
			throw new ValidateException("有错误发生");
		} else {
			json.setResult(true);
		}
	}

	/**
	 * 包装返回给页面的各级Folder数据
	 * 
	 * @param firstFolderEname
	 * @param secondFolderEname
	 * @param thirdFolderEname
	 * @param fourthFolderEname
	 * @param modelMap
	 * @return
	 * @throws FolderNotFoundException
	 */
	protected List<Folder> packageFolderByEname(String firstFolderEname,
			String secondFolderEname, String thirdFolderEname,
			String fourthFolderEname, ModelMap modelMap)
			throws FolderNotFoundException {
		List<Folder> folderPathList = new ArrayList<Folder>();
		FolderVo firstFolder = folderService.getFolderByEnameAndFatherId(
				firstFolderEname, 0);
		modelMap.addAttribute("firstFolder", firstFolder);
		modelMap.addAttribute("folder", firstFolder);
		folderPathList.add(firstFolder);
		if (StringUtils.isNotBlank(secondFolderEname)) {
			FolderVo secondFolder = folderService.getFolderByEnameAndFatherId(
					secondFolderEname, firstFolder.getFolderId());
			modelMap.addAttribute("secondFolder", secondFolder);
			modelMap.addAttribute("folder", secondFolder);
			folderPathList.add(secondFolder);
			if (StringUtils.isNotBlank(thirdFolderEname)) {
				FolderVo thirdFolder = folderService
						.getFolderByEnameAndFatherId(thirdFolderEname,
								secondFolder.getFolderId());
				modelMap.addAttribute("thirdFolder", thirdFolder);
				modelMap.addAttribute("folder", thirdFolder);
				folderPathList.add(thirdFolder);
				if (StringUtils.isNotBlank(fourthFolderEname)) {
					FolderVo fourthFolder = folderService
							.getFolderByEnameAndFatherId(fourthFolderEname,
									secondFolder.getFolderId());
					modelMap.addAttribute("fourthFolder", fourthFolder);
					modelMap.addAttribute("folder", fourthFolder);
					folderPathList.add(fourthFolder);
				}
			}
		}
		modelMap.addAttribute("folderPathList", folderPathList);
		return folderPathList;
	}
}

src/main/java/com/shishuo/cms/action/CommentAction.java
/*
 *	Copyright © 2013 Changsha Shishuo Network Technology Co., Ltd. All rights reserved.
 *	长沙市师说网络科技有限公司 版权所有
 *	http://www.shishuo.com
 */
package com.shishuo.cms.action;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.util.HtmlUtils;

import com.shishuo.cms.constant.CommentConstant;
import com.shishuo.cms.entity.vo.JsonVo;
import com.shishuo.cms.exception.ValidateException;
import com.shishuo.cms.service.ArticleService;
import com.shishuo.cms.service.CommentService;
import com.shishuo.cms.util.HttpUtils;

/**
 * @author Herbert
 * 
 */
@Controller
@RequestMapping("/comment")
public class CommentAction {
	@Autowired
	private CommentService commentService;

	@Autowired
	private ArticleService fileService;

	/**
	 * @param name
	 * @param email
	 * @param fileId
	 * @param content
	 * @param request
	 * @param modelMap
	 * @return
	 */
	@ResponseBody
	@RequestMapping(value = "/add.json", method = RequestMethod.POST)
	public JsonVo<String> add(
			@RequestParam(value = "kind") CommentConstant.kind kind,
			@RequestParam(value = "kindId") long kindId,
			@RequestParam(value = "email") String email,
			@RequestParam(value = "content") String content,
			@RequestParam(value = "name", required = false, defaultValue = "") String name,
			@RequestParam(value = "phone", required = false, defaultValue = "") String phone,
			@RequestParam(value = "company", required = false, defaultValue = "") String company,
			HttpServletRequest request, ModelMap modelMap) {
		JsonVo<String> json = new JsonVo<String>();
		try {
			if (StringUtils.isBlank(email)) {
				json.getErrors().put("email", "邮箱不能为空");
			}
			if (StringUtils.isBlank(content)) {
				json.getErrors().put("content", "内容不能为空");
			}
			json.check();
			commentService.addComment(kindId, CommentConstant.kind.folder,
					phone, email, name, HttpUtils.getIp(request),
					HtmlUtils.htmlEscape(content), company);
			return json;
		} catch (ValidateException e) {
			json.setResult(false);
			return json;
		}
	}

	@RequestMapping(value = "/page.htm", method = RequestMethod.GET)
	public String commentPage(
			@RequestParam(value = "p", defaultValue = "1") int p,
			ModelMap modelMap) {
		modelMap.put("pageVo", commentService.getCommentListPage(p, null));
		return "system/comment/list";
	}
}

src/main/java/com/shishuo/cms/action/IndexAction.java
/*
 *	Copyright © 2013 Changsha Shishuo Network Technology Co., Ltd. All rights reserved.
 *	长沙市师说网络科技有限公司 版权所有
 *	http://www.shishuo.com
 */

package com.shishuo.cms.action;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.shishuo.cms.exception.TemplateNotFoundException;

/**
 * 首页
 * 
 * @author Herbert
 */
@Controller
public class IndexAction extends BaseAction {

	/**
	 * 首页
	 * 
	 * @param pageNum
	 * @param modelMap
	 * @return
	 */
	@RequestMapping(value = "/index.htm", method = RequestMethod.GET)
	public String home(@RequestParam(value = "p", defaultValue = "1") long p,
			ModelMap modelMap) {
		try {
			modelMap.addAttribute("p", p);
			return themeService.getDefaultTemplate();
		} catch (TemplateNotFoundException e) {
			logger.fatal(e.getMessage());
			return themeService.getTemplatePath("404");
		}
	}

	/**
	 * 404
	 * 
	 * @return
	 */
	@RequestMapping(value = "/404.htm", method = RequestMethod.GET)
	public String pageNotFound() {
		return themeService.getTemplatePath("404");
	}

	/**
	 * 500
	 * 
	 * @return
	 */
	@RequestMapping(value = "/500.htm", method = RequestMethod.GET)
	public String error() {
		return themeService.getTemplatePath("500");
	}
}

src/main/webapp/themes/cms/404.ftl
<#include "header.ftl">
<style>
.page-404 {
    padding-bottom: 108px;
    padding-top: 100px;
    text-align: center;
}
.page-404 .number {
    color: #0DA3E2;
    display: inline-block;
    font-size: 128px;
    font-weight: 300;
    letter-spacing: -10px;
    line-height: 128px;
    margin-bottom: 10px;
    margin-top: 0;
    position: relative;
    text-align: right;
    top: 35px;
}
.page-404 .details {
    display: inline-block;
    margin-left: 40px;
    padding-top: 0;
    text-align: left;
}

</style>
   <!-- BEGIN PAGE CONTAINER -->  
    <div class="page-container">
  
        <!-- BEGIN BREADCRUMBS -->   
        <div class="row breadcrumbs">
            <div class="container">
                <div class="col-md-4 col-sm-4">
                    <h1>Page Not Founded</h1>
                </div>
                <div class="col-md-8 col-sm-8">
                    <ul class="pull-right breadcrumb">
                        <li><a href="${basePath}/index.htm">Home</a></li>
                        <li class="active"><a href="${basePath}/404.htm">404</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- END BREADCRUMBS -->

        <!-- BEGIN CONTAINER -->   
        <div class="container margin-bottom-40">
          <div class="row">
            <div class="col-md-12 page-404">
               <div class="number">
                  404
               </div>
               <div class="details">
                  <h3>Oops!  You're lost.</h3>
                  <p>
                     We can not find the page you're looking for.<br>
                     <a href="index.html">Return home</a> or try the search bar below.
                  </p>
                  <form action="#">
                     <div class="input-group input-medium">
                        <input type="text" placeholder="keyword..." class="form-control">
                        <span class="input-group-btn">                   
                        <button class="btn blue" type="submit"><i class="fa fa-search"></i></button>
                        </span>
                     </div>
                     <!-- /input-group -->
                  </form>
               </div>
            </div>
          </div>
        </div>
        <!-- END CONTAINER -->

  </div>
    <!-- END PAGE CONTAINER -->  
<#include "footer.ftl">

src/main/webapp/themes/cms/500.ftl
<#include "header.ftl">
<style>
.page-500 {
    padding-bottom: 100px;
    padding-top: 132px;
    text-align: center;
}
.page-500 .number {
    color: #0DA3E2;
    display: inline-block;
    font-size: 128px;
    font-weight: 300;
    letter-spacing: -10px;
    line-height: 128px;
    text-align: right;
}
.page-500 .details {
    display: inline-block;
    margin-left: 40px;
    text-align: left;
}
</style>
    <!-- BEGIN PAGE CONTAINER -->  
    <div class="page-container">
  
        <!-- BEGIN BREADCRUMBS -->   
        <div class="row breadcrumbs">
            <div class="container">
                <div class="col-md-4 col-sm-4">
                    <h1>500 Page</h1>
                </div>
                <div class="col-md-8 col-sm-8">
                    <ul class="pull-right breadcrumb">
                        <li><a href="${basePath}/index.htm">Home</a></li>
                        <li class="active"><a href="${basePath}/505.htm">500</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- END BREADCRUMBS -->

        <!-- BEGIN CONTAINER -->   
        <div class="container margin-bottom-40">
          <div class="row">
            <div class="col-md-12 page-500">
                <div class="number">
                    500
                </div>
                <div class="details">
                    <h3>Oops!  Something went wrong.</h3>
                    <p>
                        We are fixing it!<br>
                        Please come back in a while.<br><br>
                    </p>
                </div>
            </div>
          </div>
        </div>
        <!-- END CONTAINER -->

  </div>
    <!-- END PAGE CONTAINER -->  
<#include "footer.ftl">

src/main/webapp/themes/cms/article-news.ftl
<#include "header.ftl">
	<#include "topbar.ftl">
    <!--container start-->
    <div class="container">
        <div class="row">
            <!--blog start-->
            <div class="col-xs-9 ">
			<div class="panel panel-default">
				  <div class="panel-heading">${folder.name}</div>
				  <div class="panel-body">            
	            	${article.content}
                  </div>
				</div>
            </div>
			<#include "sidebar.ftl">
            <!--blog end-->
        </div>

    </div>
    <!--container end-->
<#include "footer.ftl">

src/main/webapp/themes/cms/folder-blog-photo.ftl
<#include "header.ftl">
	<#include "topbar.ftl">
    <!--container start-->
    <div class="container">
        <div class="row">
            <!--blog start-->
            <div class="col-lg-9">
				          	<@shishuocms_attachment_page  kindId="${folder.folderId}" kind="folder" p="${p}" rows="9">
				          	<#list tag_attachment_page.list as attachment>
				            <div class="col-xs-4 gallery-item">
				                <img class="img-responsive" src="${basePath}/${attachment.path}" alt="">
				            </div>
				            
				            <#if (attachment_index+1)%3==0><hr><div class="clearfix"></div></#if>
				            </#list>
				            </@shishuocms_attachment_page>			
            </div>

			<#include "sidebar.ftl">
            <!--blog end-->
        </div>

    </div>
    <!--container end-->
<#include "footer.ftl">

src/main/webapp/themes/cms/folder-contact.ftl
<#include "header.ftl">
	<#include "topbar.ftl">
    <!--container start-->
    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-sm-5 address">
                <h4>长沙市师说网络科技有限公司</h4>
                <p>
                    湖南长沙芙蓉区 <br/>
                    建湘路479号，曼哈顿大厦，1702<br/>
                </p>
                <br>
                <br>
                <br>
                <p>
                    电话：<span class="muted">0731 - 89601598</span><br/>
                    邮件：<span class="muted">cms@shishuo.com</span><br/>
                    QQ群：<span class="muted">7343505</span>
                </p>
            </div>
            <div class="col-lg-7 col-sm-7 address">
                <h4>留言</h4>
                <div class="contact-form">
                    <form role="form" id="addFeedBack" action="${basePath}/comment/add.json" method="post" autocomplete="off">
                    	<input type="hidden" name="kindId" value="${folder.folderId}">
						<input type="hidden" name="kind" value="folder">
                        <div class="form-group">
                            <label for="name">姓名</label>
                            <input type="text" placeholder="" name="name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">邮箱</label>
                            <input type="text" placeholder="" name="email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="phone">电话</label>
                            <input type="text" name="phone" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="phone">内容</label>
                            <textarea name="content" placeholder="" rows="5" class="form-control"></textarea>
                        </div>
                        <button class="btn btn-danger" type="submit">提交</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <!--container end-->
<script type="text/javascript">
	$(function(){
		$('#addFeedBack').ajaxForm(function(data){
			showErrors($('#addFeedBack'),data.errors);
			if(data.result){
				bootbox.alert("保存成功，将刷新页面", function() {
						window.location.reload();
					});
			}
		});
	});
</script>    
<#include "footer.ftl">

src/main/webapp/themes/cms/sidebar.ftl
			<!-- BEGIN RIGHT SIDEBAR -->            
            <div class="col-lg-3">
                <div class="blog-side-item">
                    <div class="category">
                        <h3>分类</h3>
                        <@shishuocms_folder_list fatherId="${firstFolder.folderId}">
                        <ul class="list-unstyled">
                        	<#list tag_folder_list as secondLevelFolder>
                            <li><a href="${basePath}/${firstFolder.ename}/${secondLevelFolder.ename}/index.htm"><i class="  icon-angle-right"></i> ${secondLevelFolder.name}</a></li>
                            </#list>
                        </ul>
                        </@shishuocms_folder_list>
                    </div>
                </div>
            </div>
			<!-- END RIGHT SIDEBAR --> 

src/main/webapp/themes/cms/topbar.ftl
	<!-- BEGIN BREADCRUMBS -->
	<div class="breadcrumbs">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-sm-4">
					<h1>${folder.name}</h1>
				</div>
				<div class="col-lg-8 col-sm-8">
					<ol class="breadcrumb pull-right">
						<#assign folderPath = "">
						<li><a href="${basePath}/index.htm">首页</a>
						</li>
						<#list folderPathList as fold> 
							<#assign folderPath = folderPath + fold.ename+"/">
							<#if fold.folderId ==folder.folderId>
							<li class="active">${fold.name}</li>
							<#else>
							<li><a href="${basePath}/${folderPath}index.htm">${fold.name}</a></li>
							</#if>
						</#list>
					</ol>
				</div>
			</div>
		</div>
	</div>
	<!-- END BREADCRUMBS -->